openapi: 3.0.0
info:
  description: This is a restful service to manage merchants
  version: '1.0'
  title: Data - Merchant Service
  termsOfService: 'http://springfox.io'
  contact:
    name: MeS SOA Team
    email: kchen@merchante-solutions.com
    url: 'http://www.merchante-solutions.com'
servers: 
  - url: 'http://localhost:9023/data/v1/'
tags:
  - name: Merchant Service
    description: Data Service to allow merchant management
paths:
  /merchants:
    get:
      tags:
        - Merchant Service
      description: Get all the merchants
      operationId: getMerchants
      parameters:
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Merchant service response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Merchant'
              example:
                - id: 1
                  name: Fast Track
                  address: 101 main street
                  phone: 111-222-1111
                - id: 2
                  name: Marry Firm
                  address: 202th street
                  phone: 111-222-1112
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Merchant Service
      description: Add a new Merchant to the system
      operationId: addMerchant
      requestBody:
        description: Merchant to add to the system
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMerchant'
      responses:
        '200':
          description: Merchant service response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
              example:
                - id: 1
                  name: John Company
                  address: 303rd revenue
                  phone: 111-222-1113
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/merchants/{id}':
    get:
      tags:
        - Merchant Service
      description: Get the merchant with the specified merhcnat id
      operationId: findMerchantWithID
      parameters:
        - name: id
          in: path
          description: merchant id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Merchant service response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
              example:
                id: 1
                name: John Limited
                address: 102 Ave
                phone: 111-222-1114
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NewMerchant:
      required: 
        - name
        - phone
      properties:
        name:
          type: string
        address:
          type: string
        phone:
          type: string
    Merchant:
      allOf:
        - $ref: '#/components/schemas/NewMerchant'
        - required:
            - id
          properties:
            id:
              type: integer
              format: int64
    Error:
      required:
        - code
        - message
      properties:
          code:
            type: integer
            format: int32
          message:
            type: string
