openapi: 3.0.0
info:
  description: This is a restful service to manage users 2
  version: '1.0'
  title: Data - User Service
  termsOfService: 'http://springfox.io'
  contact:
    name: MeS SOA Team
    email: kchen@merchante-solutions.com
    url: 'http://www.merchante-solutions.com'
servers: 
  - url: 'http://localhost:9022/data/v1/'
tags:
  - name: User Service
    description: Data Service to allow user management
paths:
  /users:
    get:
      tags:
        - User Service
      description: Get all the users
      operationId: getUsers
      parameters:
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User service response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  firstName: John
                  lastName: Doe
                  ssn: 111-222-1111
                - id: 2
                  firstName: Marry
                  lastName: Mei
                  ssn: 111-222-1112
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - User Service
      description: Add a new user to the system
      operationId: addUser
      requestBody:
        description: User to add to the system
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '200':
          description: User service response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                - id: 1
                  firstName: John
                  lastName: Doe
                  ssn: 111-222-1113
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/users/{id}':
    get:
      tags:
        - User Service
      description: Get the user with the specified user id
      operationId: findUserWithID
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User service response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 1
                firstName: John
                lastName: Joe
                ssn: 111-222-1114
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NewUser:
      required: 
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        lastName:
          type: string
        ssn:
          type: string
    User:
      allOf:
        - $ref: '#/components/schemas/NewUser'
        - required:
            - id
          properties:
            id:
              type: integer
              format: int64
    Error:
      required:
        - code
        - message
      properties:
          code:
            type: integer
            format: int32
          message:
            type: string